### ISSUE TITLE
关于Can not perform this action after onSaveInstanceState的解决方案

### ISSUE THREAD

**Issue by ChengAngel** [Othershe/NiceDialog#10]
博主，关于java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState这问题的我是这样解决的，不知道对不对，我这边测试没啥问题
   public BaseFragDialog show(FragmentManager manager) {
        if (this.isAdded()) {
            manager.beginTransaction().remove(this).commit();
        }
        FragmentTransaction ft = manager.beginTransaction();
        ft.add(this, String.valueOf(System.currentTimeMillis()));
        ft.commitAllowingStateLoss();
        //ft.show(this);
        //super.show(manager, String.valueOf(System.currentTimeMillis()));
        return this;
    }

**Comment by Othershe** [comment]
可行，网上的答案也类似
