### ISSUE TITLE
建议把dialogFragment的onCancel事件暴露出来

### ISSUE THREAD

**Issue by zsndev** [Othershe/NiceDialog#15]
议把dialogFragment的onCancel事件暴露出来，不然只是为了单纯的监听个cancel事件还需要自定义个dialog

**Comment by o03150** [comment]
我本来以为这个事件肯定是有的,结果写了一堆代码后调用,竟然没有

**Comment by dongzhixuanyuan** [comment]
确实是要暴露出来，为了这个onCancel，我自己又封装了一层。
