### ISSUE TITLE
当activity进入onPause之后，如果dialog未关闭，那么当前页面会抛异常并关闭

### ISSUE THREAD

**Issue by q876625596** [Othershe/NiceDialog#2]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object 
 Caused by: java.io.NotSerializableException

抛出以上异常

**Comment by q876625596** [comment]
找到原因，是因为onSaveInstanceState里面outState.putSerializable("listener", convertListener);这句保存状态的代码导致的

**Comment by ZhangLanqiu** [comment]
@q876625596 额，所以是你保存状态的姿势不对，跟框架没关系是吗？

**Comment by q876625596** [comment]
@ZhangLanqiu demo运行也是一样的情况

**Comment by ZhangLanqiu** [comment]
@q876625596 怎么解决的呀？ 方便的话能贴下吗

**Comment by q876625596** [comment]
@ZhangLanqiu 我是直接将NiceDialog.java这个类里面onSaveInstanceState这个方法中的outState.putSerializable("listener", convertListener);注释掉的

`/**
     * 保存接口
     *
     * @param outState
     */
    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //outState.putSerializable("listener", convertListener);
    }`

**Comment by ZhangLanqiu** [comment]
(〃'▽'〃)谢谢，看来得等博主来慢慢修复吧！

**Comment by Othershe** [comment]
@q876625596  注释掉了，旋转屏幕后接口就失效了，除非你不考虑这种情况了，我再想想别的办法吧

**Comment by q876625596** [comment]
@Othershe 是的，只是我的app是固定竖屏的，所以直接注释掉就好了。之前抛出的异常是 NotSerializableException，但是我看了一下listener是序列化过的，所以除了注释掉我也不知道怎么解决哈哈

**Comment by q876625596** [comment]
@Othershe 现在我弄了一个解决方案，就是将ViewConvertListener改成抽象类并实现Parcelable序列化，这样就不会崩溃，并且能在横竖屏切换的时候保存状态，贴一下代码：
`public abstract class ViewConvertListener implements Parcelable{

    protected abstract void convertView(ViewHolder holder, BaseNiceDialog dialog);

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
    }

    public ViewConvertListener() {
    }

    protected ViewConvertListener(Parcel in) {
    }

    public static final Creator<ViewConvertListener> CREATOR = new Creator<ViewConvertListener>() {
        @Override
        public ViewConvertListener createFromParcel(Parcel source) {
            return new ViewConvertListener(source){
                @Override
                protected void convertView(ViewHolder holder, BaseNiceDialog dialog) {

                }
            };
        }

        @Override
        public ViewConvertListener[] newArray(int size) {
            return new ViewConvertListener[size];
        }
    };
}`

**Comment by Othershe** [comment]
@q876625596  确实可行，谢谢了哦
