### ISSUE TITLE
关于loadingDialog与网络配合使用

### ISSUE THREAD

**Issue by littleWatermelonSeed** [Othershe/NiceDialog#4]
我在提交数据的时候用了一个类似于你实例中的加载提示的效果，当有网络的时候一切正常，当我开启飞行模式（没有网络）之后就报错：
![1](https://user-images.githubusercontent.com/24287239/30213031-dcb20726-94d9-11e7-8364-88b876f7db98.png)
![2](https://user-images.githubusercontent.com/24287239/30213032-dce440f6-94d9-11e7-8f49-d8c054085bfc.png)
因为我还没搞懂错误原理，所以暂时是使用先进行网络状态的判断之后再进行下一步的逻辑，如果哪位大神知道出错的原理求分享一下

**Comment by littleWatermelonSeed** [comment]
我发现问题出在哪里了
NiceDialog.init()
                .setLayoutId(R.layout.nicedialog_loading)
                .setConvertListener(new ViewConvertListener() {
                    @Override
                    public void convertView(ViewHolder viewHolder,BaseNiceDialog baseNiceDialog) {
                        baseNiceDialog.dismiss();
                    }
                })
                .setWidth(100)
                .setHeight(100)
                .setDimAmount(0)
                .setOutCancel(false)
                .show(((FragmentActivity) mContext).getSupportFragmentManager());
我测试了如上代码，结果跟我之前的的报错是一样的，所以我觉得就是回调方法里面的逻辑是可以在show()方法之前执行的，如果当我回调方法里面的逻辑处理完之后需要dismiss时NiceDialog还没有show，就会报我如上的错误
个人见解，有误请指出一下

**Comment by Othershe** [comment]
convertView()回调是在show()之后执行的，我也在网络请求中使用了，目前还没发现你说的问题，可以检查下dialog的show()和dismiss()的时机是否正确。

**Comment by littleWatermelonSeed** [comment]
我打log发现，如果我把我手机网断了，然后网络请求（网络请求逻辑是放在convertView()回调里面的，dialog.dismiss()方法是我的网络逻辑处理完之后执行的），show()方法执行之后会瞬间抛出一个网络异常，在这个时候我打log发现nicedialog.isVisible()的值为false，所以在我的逻辑处理完之后dialog还是不可见的状态，如果我在这个时候去调用dismiss()就会出错
我的解决方法如下：
handler = new Handler(){
            @Override
            public void handleMessage(Message msg) {
                super.handleMessage(msg);
                dialog.dismiss();
            }
        };

if (dialog.isVisible()){
            dialog.dismiss();
        }else {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    while (!dialog.isVisible()){

                    }
                    handler.sendEmptyMessage(0);
                }
            }).start();
        }
原理就是在需要dismiss()的时候先判断dialog是否可见，如果可见就直接dismiss()，如果不可见就开启一个线程来循环判断dialog是否可见(我做了很多测试，就是在dialog执行show方法之后没有办法让他在可见之前取消，即show之后一定会显示到界面上)，当子线程判断到dialog可见的时候就让handler把dialog给dismiss掉
