### ISSUE TITLE
包裹布局

### ISSUE THREAD

**Issue by yytangsheng** [Othershe/NiceDialog#5]
if(this.width == 0) {
                lp.width = Utils.getScreenWidth(this.getContext()) - 2 * Utils.dp2px(this.getContext(), (float)this.margin);
            } else {
                lp.width = Utils.dp2px(this.getContext(), (float)this.width);
            }

这里加个是否=-2 是不是好点  不然不能包裹了

**Comment by Othershe** [comment]
宽度 **WRAP_CONTENT** 的情况吗？

**Comment by yytangsheng** [comment]
嗯咯
