### ISSUE TITLE
Parcelable 序列化相关异常

### ISSUE THREAD

**Issue by BeginsDesign** [Othershe/NiceDialog#6]
某些情况下，在ViewConvertListener中跳转到其他activity界面会出现没有实现Parcelable 序列化的异常

**Comment by Othershe** [comment]
偶发的，还是具体某种情况下？

**Comment by ChrisTian9999** [comment]
必然情况，当没有继承Base的时候，应用切到后台  一定会崩溃

**Comment by Othershe** [comment]
这个问题在 #2 中已经修复了，目前已有的设备还没再现过
