### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by wei7785929** [Othershe/NiceDialog#7]
E/EventBus: Could not dispatch event: class com.adinnet.logistics.event.MyEventMessage to subscribing class class com.adinnet.logistics.ui.activity.driver.AccountInfoActivity
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
在使用takephoto框架后调用图片上传使用了进度条对话框，报了上面的错误

**Comment by ChengAngel** [comment]
这个问题解决了么大神，我页面淡出账号被别人挤下来的对话框时也报该错，java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

**Comment by wei7785929** [comment]
没有使用show(getFragmentManager()),用了 FragmentTransaction fragmentTransaction = getChildFragmentManager().beginTransaction();
            fragmentTransaction.add(niceProgressDialog, this.getClass().getSimpleName());
            fragmentTransaction.commitAllowingStateLoss();
你可以参考下
